services:
  app:
    build: .
    image: ghcr.io/hannahellis4242/simple-path-server/simple-path-server:latest
    ports:
      - "80:3000"
    volumes:
      - ./config:/app/config
      - ./public:/app/public
